import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Crypto tracking",
  description: "Generated by Mohmmadkm",
};

export default function ContactLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div>{children}</div>;
}
